[package]
name = "core-mx-life-bonding-sc"
version = "1.0.0"
authors = ["Bucur David - Itheum"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.47.5"

[dev-dependencies.multiversx-sc-scenario]
version = "0.47.5"

[workspace]
members = [
    ".",
    "meta",
]
