[package]
name = "core-mx-life-bonding-sc-meta"
version = "2.0.0"
edition = "2021"
publish = false

[dependencies.core-mx-life-bonding-sc]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.47.8"
default-features = false
