// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           22
// Async Callback (empty):               1
// Total number of exported functions:  24

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    core_mx_life_bonding_sc
    (
        init => init
        upgrade => upgrade
        bond => bond
        getAcceptedToken => accepted_token
        getBondToken => bond_token
        getLockPeriods => lock_periods
        getLockPeriodBondAmount => lock_period_bond_amount
        getMinimumPenalty => minimum_penalty
        getMaximumPenalty => maximum_penalty
        getWithdrawPenalty => withdraw_penalty
        getAddressBonds => address_bonds
        getBonds => bonds
        setContractStateActive => set_contract_state_active
        setContractStateInactive => set_contract_state_inactive
        setBondToken => set_bond_token
        setAcceptedToken => set_accepted_token
        setLockPeriodsAndBonds => set_lock_periods_and_bonds
        setMinimumPenalty => set_minimum_penalty
        setMaximumPenalty => set_maximum_penalty
        setWithdrawPenalty => set_withdraw_penalty
        setAdministrator => set_administrator
        getContractState => contract_state
        getAdministrator => administrator
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
